name: 'PVS-Studio scan example'
description: 'Easy way to configure PVS-Studio analyzer on GitHub'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  file-to-analyze:
    description: 'File to analyze (Compile Commands Database or trace-file)'
    required: true
  analysis-mode:
    description:
      "The group of warnings that will be activated during analysis. Several
      values must be separated by ';', e.g. 'GA;OP;64'"
    required: false
    default: 'GA;OP'
  excluded-dirs:
    description:
      'Directories whose files are not necessary to check. Several values must
      be separated by '';'', e.g.
      ''C:\dev\project\thirdparty;C:\dev\project\libs'''
    required: false
  additional-args:
    description: 'Additional args passed to analyzer'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
