name: 'PVS-Studio scan example'
description: 'Easy way to configure PVS-Studio analyzer on GitHub'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  project-file:
    description: 'File to analyze (Compile Commands Database or trace-file)'
    required: false
    default: ''
  trace-args:
    description: '[For Linux and macOS only] Allows you to trace the build tool to collect all files to analyze and their compilation options'
    required: false
    default: ''
  analysis-mode:
    description:
      "The group of warnings that will be activated during analysis. Several
      values must be separated by ';', e.g. 'GA;OP;64'"
    required: false
    default: 'GA;OP'
  output-format:
    description:
      'Render types for output. Avaliable formats can be found in documentation.'
    required: false
    default: ''
  output-file:
    description: 'Output file.'
    required: false
    default: ${{ github.workspace }}/PVS-Studio.log
  license-file:
    description: 'PVS-Studio license file'
    required: false
    default: ''
  source-tree-root:
    description: 'Replace absolute paths in report with relative paths'
    required: false
    default: ''
  parallel:
    description: 'Allow to run N PVS-Studio analyzers at once'
    required: false
    default: 0
  excluded-dirs:
    description:
      'Excludes from the report all warnings issued in certain files (wildcards
      supported). Several values must be separated by semicolon or new line,
      e.g. ''C:\dev\project\thirdparty;C:\dev\project\libs'''
    required: false
    default: ''
  suppress-files:
    description: 'Path to suppress files.'
    required: false
    default: ''
  rules-configs:
    description:
      'Paths to the diagnostics configuration file (.pvsconfig) or to the
      directory containing configuration files'
    required: false
    default: ''
  additional-args:
    description:
      'Additional args passed to analyzer. See documentation for more
      information.'
    required: false
    default: ''

outputs:
  report:
    description: 'Path to ready-to-use report in a specified format'

  raw-report:
    description:
      'Path to raw analyzer report for further conversion and processing'

runs:
  using: node20
  main: dist/index.js
